### ISSUE TITLE
Cannot install conda environment

### ISSUE THREAD

**Issue by ChenyangLEI** [andreaconti/lidar-confidence#1]
Hi, 

Thanks for your great work!

May I ask: did you try to install the conda environment?

I try to install it on two different machines but both of them cannot install the environment correctly.

Thanks!

**Comment by andreaconti** [comment]
Hi,

first of all thanks for your interest!

What kind of error do you have? Without further details I can't help you. In any case try with [mamba](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html). I tried right now with the following command it works fine on my side:

```
$ mamba env create -f environment.yml
```

**Comment by ChenyangLEI** [comment]
Error: It does not report any error but waiting for "solving the environment".

Thanks, I will try mamba first!

**Comment by ChenyangLEI** [comment]
Hi, after using the mamba, I can install the environment successfully. But I meet problem when downloading the data using dvc:

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/19903206/204274899-5696439f-97bc-4a64-b721-e8e627e622bf.png">

**Comment by andreaconti** [comment]
Happy to know that with mamba the problem is solved, I'll update the doc then. 
For the second issue I am sorry but I am not able to reproduce it, I have tried to download the data again using dvc with a different google account other than mine and it works fine.

![Screenshot from 2022-12-01 11-23-25](https://user-images.githubusercontent.com/23358927/205032110-467f4081-996d-4cd7-9d45-6feecbf7ed54.png)

The first time that you call `dvc pull` it will ask you to authenticate with a google account to download data from my shared google drive. You have to open the link it provides you, could this be the problem?
